# Generated by Django 4.2.7 on 2024-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='user',
        ),
        migrations.AddField(
            model_name='cardformat',
            name='validation_mode',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
