# Generated by Django 4.2.7 on 2024-09-04 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flash_cards_api', '0002_remove_field_user_remove_fieldvalue_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_rate', models.FloatField(default=0.1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
