# Generated by Django 4.2.7 on 2024-09-04 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flash_cards_api', '0003_card_current_streak_userpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='next_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pref', to=settings.AUTH_USER_MODEL),
        ),
    ]
