# Generated by Django 4.2.7 on 2024-09-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards_api', '0004_card_next_due_alter_userpref_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='order',
        ),
        migrations.AlterField(
            model_name='userpref',
            name='learning_rate',
            field=models.FloatField(default=0.03),
        ),
    ]
