# Generated by Django 4.2.7 on 2024-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards_api', '0005_remove_field_order_alter_userpref_learning_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataformat',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
