# Generated by Django 4.2.7 on 2024-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards_api', '0006_dataformat_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataformat',
            name='css',
        ),
        migrations.AddField(
            model_name='data',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
