# Generated by Django 4.2.7 on 2024-11-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards_api', '0007_remove_dataformat_css_data_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='css',
        ),
    ]
